provider: prometheus
service: github
display_name: Github
entities:
- name: job
  metrics:
  - provider_name: github_job
    description: job status
    type: gauge
    labels:
    - event
    - head_branch
    - head_sha
    - id
    - node_id
    - repo
    - run_number
    - status
- name: runner
  metrics:
  - provider_name: github_runner_status
    description: runner status
    type: gauge
    labels:
    - id
    - name
    - os
    - repo
    - status